version: '3.7'

services:
  omnium:
    build: .
    entrypoint: bundle exec bin/omnium
    volumes:
      - ./:/usr/src/app

  dev:
    build: .
    volumes:
      - ./:/usr/src/app

  test:
    build: .
    command: bundle exec rake

  release:
    build: .
    command: bundle exec rake signin release
